web/django/MetagenApp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n'), name="set_language"),
]

urlpatterns += i18n_patterns(
    path("", include("app.urls")),
    path('pipeline/', include("pipeline.urls")),
    path("results/", include("results.urls")),
)

web/django/app/urls.py
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = "app"
urlpatterns = [
    path("", views.index_view, name="index"),
    re_path(r'^ajax/request_lock/$', views.request_lock, name='request_lock')] \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#               + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \

web/django/pipeline/urls.py
from django.urls import path

from . import views

app_name = "pipeline"
urlpatterns = [
    path("config/", views.pipeline_config, name="config"),
    path("config/<uuid:run_id>/", views.pipeline_param_config, name="pconfig"),
    path("config/<uuid:run_id>/assign/", views.pipeline_param_assign, name="passign"),
    path("logs/", views.pipeline_logs, name="logs"),
    path("logs/<uuid:run_id>/", views.pipeline_logs_samples, name="run_logs"),
    path("logs/<uuid:run_id>/steps/", views.pipeline_logs_steps, name="run_logs_steps"),
    path("upload/", views.pipeline_upload, name="upload"),
    path("edit/", views.pipeline_edit, name="edit"),
    path("edit/edit/<uuid:run_id>", views.pipeline_run_edit, name="run_edit"),
    path("edit/delete/<uuid:run_id>", views.pipeline_delete, name="delete"),
]

web/django/results/urls.py
from django.urls import path

from . import views

app_name = "results"
urlpatterns = [
    path("<uuid:run_id>/qc/", views.results_qc, name="qc"),
    path("<uuid:run_id>/", views.results_run, name="run"),
    path("<uuid:run_id>/taxonomy/", views.results_taxonomy, name="taxonomy"),
    path("<uuid:run_id>/pcoa/", views.results_pcoa, name="pcoa"),
    path("pcoa_iframe/<uuid:plot_id>/en", views.pcoa_iframe_en, name="pcoa_iframe_en"),
    path("pcoa_iframe/<uuid:plot_id>/de", views.pcoa_iframe_de, name="pcoa_iframe_de"),
    path("kronaplot/<uuid:plot_id>", views.iframe_krona, name="krona_iframe"),
    path("qc/fastqc/<str:strand>/<uuid:sample_id>/", views.results_iframe_qc, name="qc_iframe"),
    path("qc/trim_fastqc/<str:strand>/<uuid:sample_id>", views.results_iframe_qc_trim, name="qc_iframe_trim"),
]

web/django/app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
  <meta content="" name="description">
  <meta content="" name="author">
  
  <title>MetagenApp</title>
  
  {% load static %}
  {% load i18n %}
  
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'app/materialize.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'app/custom.css' %}" rel="stylesheet" type="text/css">
  <link rel="shortcut icon" type="image/png" href="{% static 'app/img/favicon.ico' %}"/>
</head>
<body>
<header>
    {% csrf_token %}
    {% block header_include %}
    {% include "app/base_header.html" %}
    {% endblock header_include %}
</header>
<main>
  {% block content %}
  <div class="container">
    <h3 class=""></h3>
    <div class="row">
      <h1>{% trans "Data" %}</h1>
      {% for run in runs %}
      <div class="col s12 m6 l4">
        <div class="card run-card">
          <div class="card-image">
            <img alt="" class="run-img" src="{{ run.image.url }}">
            <a class="btn-floating halfway-fab waves-effect waves-light teal darken-1"
               href="{% url 'results:run' run.id %}">
              <i class="material-icons">pageview</i>
            </a>
          </div>
          <div class="run-card-content card-content">
            <span class="card-title">{{ run.analysis_en }}</span>
            {% if LANGUAGE_CODE == "en" %}
              {% if run.description_en %}
                <p>{{ run.description_en }}</p>
              {% else %}
                <p>MetagenApp run from {{ run.analysis_date|date:"d.M.Y." }}</p>
              {% endif %}
            {% else %}
              {% if run.description_de %}
                <p>{{ run.description_de }}</p>
              {% else %}
              <p>MetagenApp run from {{ run.analysis_date|date:"d.M.Y." }}</p>
            {% endif %}
            {% endif %}
          </div>
          {% if run.details_en %}
          <div class="card-action">
            <a href="#">More details</a>
          </div>
          {% else %}
          <div class="card-action">
            <a href="#"></a>
          </div>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endblock %}

</main>

  {% block footer_include %}
    <footer class="page-footer grey darken-2">
      {% include "app/base_footer.html" %}
    </footer>
  {% endblock footer_include %}


<script src="{% static 'results/vendor/js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'app/materialize.js' %}" type="text/javascript"></script>
<script src="{% static 'app/cookie_obtainer.js' %}" type="text/javascript"></script>
<!--<script src="{% static 'app/sidenav.js' %}" type="text/javascript"></script>-->
<script>

    var sidebar = $('.sidenav');

    var onOpen = function () {
        $("header, main, footer").addClass("padding-300");
    };

    var onClose = function () {
        $("header, main, footer, .nav-content").removeClass("padding-300");
        $(".nav-extended, .nav-content").removeClass("minus-300");
    };

    var get_lock = function (lock, click) {
        var trigger = $('#trigger-icon');
        var on = '<i class="material-icons teal-text" style="font-size:2rem;margin-right:0">toggle_on</i>';
        var off = '<i class="material-icons grey-text darken-3" style="font-size:2rem;margin-right:0">toggle_off</i>';
        var id_lock = $('#id_lock');
        var lock_toggle = $('#lock-toggle');
        var nav_extended = $(".nav-extended");
        if (lock === true) {
            lock_toggle.html(on);
            id_lock.attr('value', "True");
            sidebar.addClass("sidenav-fixed");
            sidebar.sidenav({"outDuration": 0, "inDuration": 0, "onCloseStart": onClose, "onOpenStart": onOpen});
            trigger.hide();
            nav_extended.addClass("minus-300");
        } else {
            lock_toggle.html(off);
            id_lock.attr('value', "False");
            sidebar.removeClass("sidenav-fixed");
            sidebar.sidenav({"outDuration": 0, "inDuration": 0, "onCloseStart": onClose, "onOpenStart": onOpen});
            trigger.show();
            nav_extended.removeClass("minus-300");
            if (click === true) {
                trigger.click()
            }
        }
    };

    var update_lock = function (click) {
        var is_locked = $('#id_lock').attr("value");
        $.ajax({
            url: '{% url "app:request_lock" %}',
            data: {
                'is_locked': is_locked,
            },
            dataType: 'json',
            type: "POST",
            success: function (data) {
                get_lock(data.response, click)
            }
        });
    };

    $(document).ready(function () {
        $('.collapsible').collapsible();
        $('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
        $('.dropdown-trigger').dropdown({constrainWidth: false });
        get_lock( {{ session.sn_lock|yesno:"true,false,maybe" }} , false);
        $('select').formSelect();
    });

    $("#lock-side-nav").click(function () {
        update_lock(true)
    });

    $('#check').change(function () {
        if ($(this).is(':checked')) {
            $('input[name="samples_form-samples"]').prop('checked', "checked");
        } else {
            $('input[name="samples_form-samples"]').prop('checked', false);
        }
        $("#form").submit();
    });

    $('input[type=checkbox], input[type=radio]').on('change', function () {
        if ($(this).attr("name") === "samples_form-samples") {
             $("#form").submit();
        }
                if ($(this).attr("name") === "steps_form-step") {
             $("#steps-form").submit();
        }
       
    });
    
    $('.lang-select').click( function(e) {
        e.preventDefault();
        $("input[name='language']").val( $(this).attr("id"));
       $("#lang-form").submit();
    });
    
    $('.lang-select2').click( function(e) {
        e.preventDefault();
        $("input[name='language']").val( $(this).attr("id").slice(0,-1));
        $("#lang-form").submit();
    });


    var addEvent = function (object, type, callback) {
        if (object == null || typeof (object) == 'undefined') return;
        if (object.addEventListener) {
            object.addEventListener(type, callback, {passive: true});
        } else if (object.attachEvent) {
            object.attachEvent("on" + type, callback);
        } else {
            object["on" + type] = callback;
        }
    };

    addEvent(window, "resize", function () {
        if ($(window).width() < 992 && sidebar.hasClass("sidenav-fixed")) {
            $('#trigger-icon').show();
        }
        if ($(window).width() >= 992 && sidebar.attr("id") === "sidebar-nofix") {
            sidebar.sidenav("close");
        }
    });

    addEvent(sidebar, "click", function () {
        $(".nav-extended").removeClass("minus-300");
    });
    
    
</script>
{% block custom_js %}

{% endblock %}
</body>
</html>

web/django/app/templates/app/base_footer.html
{% load i18n %}


<div class="container">
  <div class="row">
    <div class="col s11">
      <p>{% trans "Page footer" %}</p>
    </div>
    <div class="col s1 right">
      <div class="valign-wrapper">
      </div>
    </div>
  </div>
</div>
<div class="footer-copyright grey darken-3">
  <div class="container">
    <div class="row ">
      <div class="col">
        <p class="white-text">© Copyright 2019 - {% trans "all rights reserved, University of Applied Sciences, Vienna; Design by" %} Josef W. Moser Msc. </p>
      </div>
    </div>
  </div>
</div>

web/django/app/templates/app/base_header.html
{% load i18n %}
{% load static %}
<div class="navbar-fixed">
  <nav class="nav-extended">
    <div class="nav-wrapper teal " id="header">
      <div class="container">
        <a class="sidenav-trigger left" data-target="sidebar-nofix" href="#" id="sidebar-trigger">
          <i class="material-icons" id="trigger-icon">menu</i>
        </a>
        <a class="navbar-brand" href="#">MetagenApp</a>
        <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'app:index' %}"><i class="material-icons" >home</i></a></li>
          <li><a class='dropdown-trigger' data-target='pipeline-dd' href='#' style="padding-right: 0;padding-left: 0.3em">
            <img alt="Runs" src="{% static 'app/img/data.svg' %}" width="60px" style="transform: translateY(25%);">
          </a>
            <ul class='dropdown-content' id='pipeline-dd'>
              <li><a href="{% url 'pipeline:config' %}">{% trans "New Run" %}</a></li>
              <li class="divider" tabindex="-1"></li>
              <li><a href="{% url 'pipeline:logs' %}">{% trans "View Logs" %}</a></li>
              <li class="divider" tabindex="-1"></li>
              <li><a href="{% url 'pipeline:upload' %}">{% trans "Upload Run" %}</a></li>
              <li class="divider" tabindex="-1"></li>
              <li><a href="{% url 'pipeline:edit' %}">{% trans "Edit Run" %}</a></li>
            </ul>
          </li>
          <li><a class='dropdown-trigger' data-target='results-dd' href='#' style="padding-right: 0.3em;padding-left: 0.3em">
            <img id="results-dd-img" alt="Runs" src="{% static 'app/img/research.svg' %}" width="50px" style=" transform: translateY(25%);">
          </a>
            <ul class='dropdown-content' id='results-dd'>
              {% for run in runs %}
              <li><a href="{% url 'results:run' run.id %}">{{ run.analysis_en }}</a></li>
              {%endfor %}
            </ul>
          </li>
          <li>
            <a class='dropdown-trigger' data-target='lang' href='#'>
              <i class="material-icons right " style="margin-left: 3px">arrow_drop_down</i>
              {% get_current_language as LANGUAGE_CODE %}
              <i class="material-icons left dd-icon" style="margin-right: 5px">language</i>
              {% if LANGUAGE_CODE == "en" %} en {% else %} de {% endif %}</a>
            <ul class='dropdown-content' id='lang'>
              <form action="{% url 'set_language' %}" id="lang-form" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ request.get_full_path  }}">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                <input name="language" type="hidden">
                {% for language in languages %}
                <li><a class="lang-select" href="" id="{{ language.code }}">{{ language.name_local }}</a></li>
                {% endfor %}
              </form>
            </ul>
          </li>
        </ul>
      </div>
      {% block horizontal_menu %}
      {% endblock %}
    </div>
  </nav>
</div>
<!--    <li class="brand-logo teal darken-2 white-text z-depth-2 hide-on-med-and-down">Metagenapp</li>-->
<form action="" enctype="multipart/form-data" id="form" method="POST">
  <ul class="sidenav collapsible" id="sidebar-nofix">
    <li class="hide-on-large-only" id="menu-item">
      <ul class="collapsible">
        <li class="active">
          <div class="collapsible-header">{% trans "Menu" %}</div>
          <div class="collapsible-body">
            <ul>
              <li><a href="{% url 'app:index' %}">Home</a></li>
              <li>
                <a class='dropdown-trigger' data-target='pipeline-dd2' href='#'>Pipeline
                  <i class="material-icons right">arrow_drop_down</i> </a>
                <ul class='dropdown-content' id='pipeline-dd2'>
                  <li><a href="{% url 'pipeline:config' %}">{% trans "New Run" %}</a></li>
                  <li class="divider" tabindex="-1"></li>
                  <li><a href="{% url 'pipeline:logs' %}">{% trans "View Logs" %}</a></li>
                  <li class="divider" tabindex="-1"></li>
                  <li><a href="{% url 'pipeline:upload' %}">{% trans "Upload Run" %}</a></li>
                  <li class="divider" tabindex="-1"></li>
                  <li><a href="{% url 'pipeline:edit' %}">{% trans "Edit Run" %}</a></li>
                </ul>
              </li>
              <li>
                <a class='dropdown-trigger' data-target='results-dd2' href='#'>{% trans "Runs" %}
                  <i class="material-icons right ">arrow_drop_down</i> </a>
                <ul class='dropdown-content' id='results-dd2'>
                  {% for run in runs %}
                  <li><a href="{% url 'results:run' run.id %}">run.analysis_en</a></li>
                  {%endfor %}
                </ul>
              </li>
              <li>
                <a class='dropdown-trigger' data-target='lang2' href='#'>
                  <i class="material-icons right " style="margin-left: 3px">arrow_drop_down</i>
                  {% get_current_language as LANGUAGE_CODE %}
                  <i class="material-icons left dd-icon" style="margin-right: 5px">language</i>
                  {% if LANGUAGE_CODE == "en" %} en {% else %} de {% endif %}</a>
                <ul class='dropdown-content' id='lang2'>
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                    <li><a class="lang-select2" href="" id="{{ language.code }}2">{{ language.name_local }}</a></li>
                    {% endfor %}
                </ul>
              </li>
            </ul>
          </div>
        </li>
        <li class="divider no-margin"></li>
        {% block sidenav_items %}
        {% endblock %}
      </ul>
    </li>
  
  </ul>
</form>

web/django/app/templates/app/base_header_fixed.html
{% load materializecss %}
{% load static %}
{% load i18n %}
<div class="navbar-fixed">
  <nav class="nav-extended">
    <div class="nav-wrapper teal" id="header">
      <div class="container">
        <a class="sidenav-trigger show-on-large button-collapse" data-target="sidebar" href="#" id="sidebar-trigger">
          <i class="material-icons" id="trigger-icon">menu</i>
        </a>
        <a class="navbar-brand" href="#">MetagenApp</a>
        <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'app:index' %}"><i class="material-icons" style="margin-left: 3px">home</i></a></li>
          <li><a class='dropdown-trigger' data-target='pipeline-dd' href='#' style="padding-right: 0;padding-left: 0.3em">
            <img alt="Runs" src="{% static 'app/img/data.svg' %}" width="60px" style="transform: translateY(30%);">
          </a>
            <ul class='dropdown-content' id='pipeline-dd'>
              <li><a href="{% url 'pipeline:config' %}">{% trans "New Run" %}</a></li>
              <li class="divider" tabindex="-1"></li>
              <li><a href="{% url 'pipeline:logs' %}">{% trans "View Logs" %}</a></li>
              <li class="divider" tabindex="-1"></li>
              <li><a href="{% url 'pipeline:upload' %}">{% trans "Upload Run" %}</a></li>
              <li class="divider" tabindex="-1"></li>
              <li><a href="{% url 'pipeline:edit' %}">{% trans "Edit Run" %}</a></li>
            </ul>
          </li>
          
          <li>
            <li><a class='dropdown-trigger' data-target='results-dd' href='#' style="padding-right: 0.3em;padding-left: 0.3em">
            <img id="results-dd-img" alt="Runs" src="{% static 'app/img/research.svg' %}" width="50px" style=" transform: translateY(25%);">
          </a>
            <ul class='dropdown-content' id='results-dd'>
              <li class="grey lighten-3"><span class="grey-text darken-4">{% trans "Show results:" %}</span></li>
              {% for run in runs %}
              <li><a href="{% url 'results:run' run.id %}"> {{run.analysis_en }}</a></li>
              {%endfor %}
            
            </ul>
          </li>
          <li>
            <a class='dropdown-trigger' data-target='lang' href='#'>
              <i class="material-icons right " style="margin-left: 3px">arrow_drop_down</i>
              {% get_current_language as LANGUAGE_CODE %}
              <i class="material-icons left dd-icon" style="margin-right: 5px">language</i>
              {% if LANGUAGE_CODE == "en" %} en {% else %} de {% endif %}</a>
            <ul class='dropdown-content' id='lang'>
              <form action="{% url 'set_language' %}" id="lang-form" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ request.get_full_path  }}">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                <input name="language" type="hidden">
                {% for language in languages %}
                <li><a class="lang-select" href="" id="{{ language.code }}">{{ language.name_local }}</a></li>
                {% endfor %}
              </form>
            </ul>
          </li>
        </ul>
      </div>
      {% block horizontal_menu %}
      {% endblock %}
    </div>
  </nav>
</div>
<form action="" enctype="multipart/form-data" id="form" method="POST">
  {% csrf_token %}
  <ul class="sidenav collapsible" id="sidebar">
    <li>
      <div class=" row fix-sn-row collapsible-header grey lighten-4">
        <a class=" hide-on-med-and-down" id="lock-side-nav">
          <div class=" col s6" style="padding: 0; margin: 0;">{% trans "Sidebar lock" %}</div>
          <div class="col s6 right-align" style="padding: 0">
            <i class="material-icons grey-text text-darken-3"
               style="font-size: 1.2rem; vertical-align: 12%;margin-right:0">lock_open</i>
            <span id="lock-toggle"><i class="material-icons teal-text"
                                      style="font-size: 2rem;margin-right:0">toggle_on</i></span>
            <i class="material-icons grey-text text-darken-3"
               style="font-size: 1.2rem; vertical-align: 12%;margin-right:0">lock</i>
          </div>
          <form action="" id="lock-form" method="POST">
            {{ lock_form }}
          </form>
        </a>
      </div>
      <div class="collapsible-body"></div>
    </li>
    <li class="hide-on-large-only" id="menu-item">
      <div class="collapsible-header">{% trans "Menu" %}</div>
      <div class="collapsible-body">
        <ul>
          <li><a href="{% url 'app:index' %}">Home</a></li>
          <li>
            <a class='dropdown-trigger' data-target='pipeline-dd2' href='#'>Pipeline
              <i class="material-icons right dd-icon">arrow_drop_down</i> </a>
            <ul class='dropdown-content' id='pipeline-dd2'>
              <li><a href="{% url 'pipeline:config' %}">{% trans "New Run" %}</a></li>
              <li class="divider" tabindex="-1"></li>
              <li><a href="{% url 'pipeline:logs' %}">{% trans "View Logs" %}</a></li>
              <li class="divider" tabindex="-1"></li>
              <li><a href="{% url 'pipeline:upload' %}">{% trans "Upload Run" %}</a></li>
              <li class="divider" tabindex="-1"></li>
              <li><a href="{% url 'pipeline:edit' %}">{% trans "Edit Run" %}</a></li>
            </ul>
          </li>
          <li>
            <a class='dropdown-trigger image-icon' data-target='results-dd2' href='#'>{% trans "Runs" %}
              <i class="material-icons right dd-icon">arrow_drop_down</i> </a>
            <ul class='dropdown-content' id='results-dd2'>
              {% for run in runs %}
              <li><a href="{% url 'results:run' run.id %}">{{run.analysis_en}}</a></li>
              {%endfor %}
            </ul>
          </li>
          <li>
            <a class='dropdown-trigger' data-target='lang2' href='#'>
              <i class="material-icons right " style="margin-left: 3px">arrow_drop_down</i>
              {% get_current_language as LANGUAGE_CODE %}
              <i class="material-icons left dd-icon" style="margin-right: 5px">language</i>
              {% if LANGUAGE_CODE == "en" %} en {% else %} de {% endif %}</a>
            <ul class='dropdown-content' id='lang2'>
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
              <li><a class="lang-select2" href="" id="{{ language.code }}2">{{ language.name_local }}</a></li>
              {% endfor %}
            </ul>
          </li>
        </ul>
      </div>
    </li>
    <li class="divider no-margin hide-on-large-only"></li>
    {% block sidenav_items %}
    {% endblock %}
  </ul>
</form>