web/django/MetagenApp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n'), name="set_language"),
]

urlpatterns += i18n_patterns(
    path("", include("app.urls")),
    path('pipeline/', include("pipeline.urls")),
    path("results/", include("results.urls")),
)

web/django/app/urls.py
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = "app"
urlpatterns = [
    path("", views.index_view, name="index"),
    re_path(r'^ajax/request_lock/$', views.request_lock, name='request_lock')] \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#               + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \

web/django/results/urls.py
from django.urls import path

from . import views

app_name = "results"
urlpatterns = [
    path("<uuid:run_id>/qc/", views.results_qc, name="qc"),
    path("<uuid:run_id>/", views.results_run, name="run"),
    path("<uuid:run_id>/taxonomy/", views.results_taxonomy, name="taxonomy"),
    path("<uuid:run_id>/pcoa/", views.results_pcoa, name="pcoa"),
    path("pcoa_iframe/<uuid:plot_id>/en", views.pcoa_iframe_en, name="pcoa_iframe_en"),
    path("pcoa_iframe/<uuid:plot_id>/de", views.pcoa_iframe_de, name="pcoa_iframe_de"),
    path("kronaplot/<uuid:plot_id>", views.iframe_krona, name="krona_iframe"),
    path("qc/fastqc/<str:strand>/<uuid:sample_id>/", views.results_iframe_qc, name="qc_iframe"),
    path("qc/trim_fastqc/<str:strand>/<uuid:sample_id>", views.results_iframe_qc_trim, name="qc_iframe_trim"),
]

web/django/results/models.py
import os
import uuid

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey


class PipelineRun(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)
    analysis_en = models.CharField(_("english name"),
                                   max_length=20,
                                   unique=True)
    analysis_de = models.CharField(_("german name"),
                                   max_length=20,
                                   blank=True)
    mode = models.CharField(_("mode"),
                            choices=[(x, x) for x in ["WGS", "16S"]],
                            default="16S",
                            max_length=3)
    cpu_cores = models.IntegerField(_("CPU cores"),
                                    choices=[(x, x) for x in range(1, os.cpu_count() + 1)],
                                    default=os.cpu_count() - 1)
    analysis_date = models.DateTimeField(_("date"), default=timezone.now)
    status = models.CharField(max_length=10, default="new")
    description_en = models.TextField(_("description (en)"), max_length=500, blank=True)
    description_de = models.TextField(_("description (ge)"), max_length=500, blank=True)
    details_en = models.TextField(_("detailed description (en)"), max_length=10000, blank=True)
    details_de = models.TextField(_("detailed description (ge)"), max_length=10000, blank=True)
    image = models.ImageField(_("image"), blank=True)

    def __str__(self):
        return self.analysis_en


def set_upload_path(instance, filename):
    return f"input/{instance.run.analysis_en}/{filename}"


class Sample(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    run = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    name = models.CharField(_("Sample Name"), max_length=20)
    sample_file_fwd = models.FileField(_("forward file"), upload_to=set_upload_path)
    sample_file_rev = models.FileField(_("reverse file"), upload_to=set_upload_path)


class KronaPlot(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    run_id = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    sample_id = models.ForeignKey(Sample, on_delete=models.CASCADE)
    kronahtml = models.TextField("kronahtml")


class EmperorPlot(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    run_id = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    rank = models.CharField("rank", max_length=1)
    emperordata_en = models.TextField("emperordata")
    emperordata_de =  models.TextField("emperordata", blank=True, null=True)


class Taxon(MPTTModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True,
                            related_name="children")
    sample_id = models.ForeignKey(Sample, on_delete=models.CASCADE)
    run_id = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    percentage = models.FloatField()
    fragments_root = models.IntegerField()
    fragments = models.IntegerField()
    abundance = models.IntegerField()
    rank = models.CharField(max_length=4)
    tax_id = models.CharField(max_length=30, blank=True, null=True)
    name = models.CharField(max_length=200)

    class MPTTMeta:
        order_insertion_by = ['name']


class SampleParameterPreset(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    run = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    parameter_en = models.CharField("parameter (english)", max_length=20)
    parameter_de = models.CharField("parameter (german)", max_length=20)
    datatype = models.CharField(_("data type"), max_length=11)
    value_1 = models.CharField(_("value 1"), max_length=20, blank=True, null=True)
    value_2 = models.CharField(_("value 2"), max_length=20, blank=True, null=True)
    value_3 = models.CharField(_("value 3"), max_length=20, blank=True, null=True)
    value_4 = models.CharField(_("value 4"), max_length=20, blank=True, null=True)
    value_5 = models.CharField(_("value 5"), max_length=20, blank=True, null=True)
    value_6 = models.CharField(_("value 6"), max_length=20, blank=True, null=True)
    value_7 = models.CharField(_("value 7"), max_length=20, blank=True, null=True)
    value_8 = models.CharField(_("value 8"), max_length=20, blank=True, null=True)
    value_9 = models.CharField(_("value 9"), max_length=20, blank=True, null=True)
    value_10 = models.CharField(_("value 10"), max_length=20, blank=True, null=True)
    value_1_de = models.CharField(_("value 1 (ge)"), max_length=20, blank=True, null=True)
    value_2_de = models.CharField(_("value 2 (ge)"), max_length=20, blank=True, null=True)
    value_3_de = models.CharField(_("value 3 (ge)"), max_length=20, blank=True, null=True)
    value_4_de = models.CharField(_("value 4 (ge)"), max_length=20, blank=True, null=True)
    value_5_de = models.CharField(_("value 5 (ge)"), max_length=20, blank=True, null=True)
    value_6_de = models.CharField(_("value 6 (ge)"), max_length=20, blank=True, null=True)
    value_7_de = models.CharField(_("value 7 (ge)"), max_length=20, blank=True, null=True)
    value_8_de = models.CharField(_("value 8 (ge)"), max_length=20, blank=True, null=True)
    value_9_de = models.CharField(_("value 9 (ge)"), max_length=20, blank=True, null=True)
    value_10_de = models.CharField(_("value 10 (ge)"), max_length=20, blank=True, null=True)


class SampleParameter(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sample = models.ForeignKey(Sample, on_delete=models.CASCADE)
    run = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    name_en = models.CharField(_("parameter (english)"), max_length=20)
    name_de = models.CharField(_("parameter (german)"), max_length=20)
    value = models.CharField(_("value"), max_length=20)
    value_de = models.CharField(_("value (german)"), max_length=20)
    datatype = models.CharField(_("type"), max_length=11)
    order = models.IntegerField(null=True)


class PipelineQC(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    run_id = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    sample_id = models.ForeignKey(Sample, on_delete=models.CASCADE)
    fastqc_fwd = models.TextField("fastqc_fwd")
    fastqc_rev = models.TextField("fastqc_rev")
    fastqc_fwd_trim = models.TextField("fastqc_fwd_trim", default="")
    fastqc_rev_trim = models.TextField("fastqc_rev_trim", default="")

web/django/results/forms.py
from django import forms
from .models import Sample
from django.utils.translation import gettext_lazy as _


class StrandMenu(forms.Form):
    def __init__(self, *args, **kwargs):
        super(StrandMenu, self).__init__(*args, **kwargs)
        self.initial['strand'] = 'fastqc_fwd'

    choices = [("fastqc_fwd", _("Forward")),
               ("fastqc_rev", _("Reverse"))]
    strand = forms.ChoiceField(label=_("strand"),
                               widget=forms.RadioSelect(attrs={"class": "radio-form"}),
                               choices=choices,
                               required=True)


class SampleMenu(forms.Form):
    class Meta:
        model = Sample
        fields = ('name',)

    def __init__(self, *args, qs=None, session=None, **kwargs):
        super(SampleMenu, self).__init__(*args, **kwargs)
        initial = session.active_samples if session else []
        if qs:
            qs = [[x.id, x.name] for x in reversed(qs)]
            self.fields['samples'] = forms.MultipleChoiceField(choices=qs,
                                                               widget=forms.CheckboxSelectMultiple(),
                                                               required=False,
                                                               label="",
                                                               initial=initial)


class SampleMenuRadio(forms.Form):
    class Meta:
        model = Sample
        fields = ('name',)

    def __init__(self, *args,  qs=None, **kwargs):
        super(SampleMenuRadio, self).__init__(*args, **kwargs)
        if qs:
            qs = [(str(x.id), x.name) for x in reversed(qs)]
            self.fields['samples'] = forms.ChoiceField(choices=qs,
                                                       widget=forms.RadioSelect(attrs={"class": "radio-form"}),
                                                       required=True,
                                                       label="")


class RankMenu(forms.Form):
    def __init__(self, *args, **kwargs):
        super(RankMenu, self).__init__(*args, **kwargs)
        self.initial['rank'] = 'S'

    choices = [("S", _("Species")),
               ("G", _("Genus")),
               ("F", _("Family")),
               ("O", _("Order")),
               ("C", _("Class")),
               ("P", _("Phylum"))]
    rank = forms.ChoiceField(label="",
                               widget=forms.RadioSelect(attrs={"class": "radio-form"}),
                               choices=choices,
                               required=True)

web/django/results/views.py
from django.shortcuts import render
from django.views.decorators.clickjacking import xframe_options_exempt

from app.session_controller import SessionController, update_session
from .forms import SampleMenu, SampleMenuRadio, RankMenu, StrandMenu
from .models import PipelineRun, Sample, KronaPlot, EmperorPlot, PipelineQC, SampleParameterPreset


@update_session
def results_run(request, run_id):
    template_name = "results/results.html"
    runs = PipelineRun.objects.all()

    if request.method == 'GET':
        return render(request, template_name, {
            "runs": runs,
        })


@update_session
def results_qc(request, run_id):
    template_name = "results/qc.html"
    samples = Sample.objects.filter(run_id=run_id)
    session = SessionController(request)
    qcs = None
    strand = None
    strand_trim = None

    if request.method == "POST":
        samples_form = SampleMenuRadio(request.POST, qs=samples, prefix="samples_form")
        strand_form = StrandMenu(request.POST, prefix="strand_form")
        if samples_form.is_valid() and strand_form.is_valid():
            qcs = PipelineQC.objects.filter(sample_id=session.active_samples[0], run_id=run_id)
            strand = strand_form.cleaned_data["strand"]
            strand_trim = strand + "_trim"

        else:
            samples_form = SampleMenuRadio(qs=samples,
                                           prefix="samples_form")
    else:
        try:
            initial = {"samples_form-samples": session.active_samples[0]}
            qcs = PipelineQC.objects.filter(sample_id=session.active_samples[0], run_id=run_id)
        except IndexError:
            initial = {}
        samples_form = SampleMenuRadio(initial, qs=samples, prefix="samples_form")
        strand_form = StrandMenu(prefix="strand_form", initial={"strand": "fastqc_fwd"})

    return render(request, template_name, {
        "runs": PipelineRun.objects.all(),
        "samples_form": samples_form,
        "strand_form": strand_form,
        "qcs": qcs,
        "strand": strand,
        "strand_trim": strand_trim
    })


@xframe_options_exempt
def results_iframe_qc(request, sample_id, strand):
    template_name = "results/qc_iframe.html"
    fastqc = PipelineQC.objects.get(sample_id=sample_id)
    content = fastqc.fastqc_fwd if strand == "fastqc_fwd" else fastqc.fastqc_rev
    return render(request, template_name, {"content": content})


@xframe_options_exempt
def results_iframe_qc_trim(request, sample_id, strand):
    template_name = "results/qc_iframe_trim.html"
    fastqc = PipelineQC.objects.get(sample_id=sample_id)
    content = fastqc.fastqc_fwd_trim if strand == "fastqc_fwd_trim" else fastqc.fastqc_rev_trim
    return render(request, template_name, {"content": content})


@update_session
def results_taxonomy(request, run_id):
    template_name = "results/taxonomy.html"
    samples = Sample.objects.filter(run_id=run_id)
    session = SessionController(request)
    kronaplots = KronaPlot.objects.filter(sample_id__in=session.active_samples, run_id=run_id)

    if request.method == "POST":
        samples_form = SampleMenu(request.POST, qs=samples, prefix="samples_form", session=session)

    else:
        samples_form = SampleMenu(qs=samples, prefix="samples_form", session=session)

    return render(request, template_name, {
        "runs": PipelineRun.objects.all(),
        "samples_form": samples_form,
        "kronaplots": kronaplots,
    })


@xframe_options_exempt
def iframe_krona(request, plot_id):
    template_name = "results/krona_iframe.html"
    plot = KronaPlot.objects.get(pk=plot_id)
    content = plot.kronahtml
    return render(request, template_name, {"content": content})


@xframe_options_exempt
def pcoa_iframe_en(request, plot_id):
    template_name = "results/pcoa_iframe.html"
    plot = EmperorPlot.objects.get(pk=plot_id)
    emperordata = plot.emperordata_en
    print(emperordata)

    return render(request, template_name, {"emperordata": emperordata})


@xframe_options_exempt
def pcoa_iframe_de(request, plot_id):
    template_name = "results/pcoa_iframe.html"
    plot = EmperorPlot.objects.get(pk=plot_id)
    emperordata = plot.emperordata_de

    return render(request, template_name, {"emperordata": emperordata})

@update_session
def results_pcoa(request, run_id):
    template_name = "results/pcoa.html"
    runs = PipelineRun.objects.all()
    rank = "S"

    if request.method == "POST":
        rankform = RankMenu(request.POST)
        if rankform.is_valid():
            rank = rankform.cleaned_data["rank"]

    else:
        rankform = RankMenu(initial={"rank": rank})

    emperorplot = EmperorPlot.objects.get(run_id=run_id, rank=rank)

    return render(request, template_name, {
        "runs": runs,
        "rankform": rankform,
        "plot": emperorplot,
    })

web/django/results/templates/results/krona_iframe.html
{{ content|safe }}

web/django/results/templates/results/pcoa.html
{% extends "results/results.html" %}
{% load materializecss %}
{% csrf_token %}
{% block header_include %}
{% include "results/pcoa_header.html" %}
{% endblock header_include %}
{% csrf_token %}
{% block content %}
<div>
  {% if LANGUAGE_CODE == "en" %}
    <iframe class="pcoa-iframe"  src='{% url "results:pcoa_iframe_en" plot.id %}'></iframe>
  {% else %}
    <iframe class="pcoa-iframe"  src='{% url "results:pcoa_iframe_de" plot.id %}'></iframe>
  {% endif %}
</div>
{% endblock content %}

{% block custom_js %}
<script>
  $(document).ready(function () {
      $('footer').prop("hidden", true);
      var rc = $('#results-collapsible');
      rc.removeClass("active");
      rc.find(".collapsible-body").css("display", "none");
      $('.collapsible').collapsible();
  });
  
    $('input[type=radio]').on('change', function () {
    $("#form").submit();
});
</script>
{% endblock %}

web/django/results/templates/results/pcoa_header.html
{% extends "results/results_header.html" %}
{% load i18n %}
{% load materializecss %}


{% block sidenav_items_2 %}

<div class="divider no-margin"></div>
<li class="active">
  <div class="collapsible-header">{% trans "Taxonomic Rank" %}</div>
  <div class="collapsible-body">
    <ul>
      {{ rankform|materializecss }}
    </ul>
  </div>
</li>
{% endblock %}

web/django/results/templates/results/qc.html
{% extends "app/base.html" %}
{% load materializecss %}

{% block header_include %}
{% include "results/qc_header.html" %}
{% endblock header_include %}

{% block content %}


<div class="row" style="margin: 0; flex: 1 0 auto;">
  {% for qc in qcs %}
  <div class="col s12 m12 l6" style="padding:0;flex: 1 0 auto;">
    <iframe class="qc-iframe" id="qc1" src='{% url "results:qc_iframe" strand qc.sample_id.id %}'></iframe>
  </div>
  <div class="col s12 m12 l6" style="padding:0">
    <iframe class="qc-iframe" id="qc2"
            src='{% url "results:qc_iframe_trim" strand_trim qc.sample_id.id %}'></iframe>
  </div>
  {% endfor %}
</div>

{% endblock content %}

{% block custom_js %}
<script>
    $(window).load(
        function () {
            $('footer').prop("hidden", true);
            $("#qc1").contents().find('div.main').css("overflow-y", "hidden");
            $("#qc2").contents().find('div.main').on('scroll', function () {
                $("#qc1").contents().find('div.main').scrollTop($(this).scrollTop());
            });
            $("#qc1").contents().find('div.main').on('scroll', function () {
                $("#qc2").contents().find('div.main').scrollTop($(this).scrollTop());
            })
        }
    );

    addEvent(window, "resize", function () {
        if ($(window).width() < 992) {
            $("#qc1").contents().find('div.main').css("overflow-y", "scroll");
        } else {
            $("#qc1").contents().find('div.main').css("overflow-y", "hidden");
        }
    });

    $(document).ready(function () {
        var rc = $('#results-collapsible');
        rc.removeClass("active");
        rc.find(".collapsible-body").css("display", "none");
        $('.collapsible').collapsible();

    });
</script>

{% load static %}
<script src="{% static 'menu_handler_qc.js' %}" type="text/javascript"></script>

{% endblock %}

web/django/results/templates/results/qc_header.html
{% extends "results/results_header.html" %}
{% load materializecss %}
{% load i18n %}
{% block sidenav_items_2 %}

<div class="divider no-margin"></div>
<li>
  <div class="collapsible-header">{% trans "Strand" %}</div>
  <div class="collapsible-body">
    <ul>
      {{ strand_form.strand|materializecss }}
    </ul>
  </div>
</li>
<div class="divider no-margin"></div>
<li class="active" id="samples-collapsible">
  <div class="collapsible-header">{% trans "Samples" %}</div>
  <div class="collapsible-body">
    {{ samples_form|materializecss }}
  </div>
</li>

{% endblock %}

web/django/results/templates/results/qc_iframe.html
{{ content|safe }}

web/django/results/templates/results/qc_iframe_trim.html
{{ content|safe }}

web/django/results/templates/results/results.html
{% extends "app/base.html" %}
{% load staticfiles%}
{% block header_include %}
{% include "results/results_header.html" %}
{% endblock header_include %}
{% load i18n %}
{% block content %}

<div class="container">
  <h3 class=""></h3>
  <div class="row">
        <div class="col s12 m4">
      <a href="{% url 'results:qc' session.active_run  %}">
        <div class="card teal lighten-2 center">
          <div class="card-content">
            <img alt="" class="plot-icon" src="{% static 'app/img/box-plot.svg' %}" height="100px">
            <span class="card-title white-text"><b>{% trans "Quality Control" %}</b></span>
          </div>
        </div>
      </a>
    </div>
    <div class="col s12 m4">
      <a href="{% url 'results:taxonomy' session.active_run %}">
        <div class="card teal lighten-2 center">
          <div class="card-content">
            <img alt="" class="plot-icon" src="{% static 'app/img/ico_krona.svg' %}" height="100px">
            <span class="card-title white-text"><b>{% trans "Taxonomy" %}</b></span>
          </div>
        </div>
      </a>
    </div>
  {% if session.emperor %}
    <div class="col s12 m4">
      <a href="{% url 'results:pcoa' session.active_run %}">
        <div class="card teal lighten-2 center">
          <div class="card-content">
            <img alt="" class="plot-icon" src="{% static 'app/img/biplot-icon.svg' %}" height="100px">
            <span class="card-title white-text"><b>{% trans "Principal Coordinates Analysis" %}</b></span>
          </div>
        </div>
      </a>
    </div>
  </div>
  {% endif %}
</div>

{% endblock %}

  {% block footer_include %}
  {% endblock footer_include %}

web/django/results/templates/results/results_header.html
{% extends "app/base_header_fixed.html" %}
{% load i18n %}
{% block sidenav_items %}
<li class="active" id="results-collapsible">
  <div class="collapsible-header">{% trans "Results" %}</div>
  <div class="collapsible-body">
    <ul class="collapsible">
      <li><a href="{% url 'results:qc' session.active_run  %}">QC</a></li>
      <li class="divider" tabindex="-1"></li>
      <li><a href="{% url 'results:taxonomy' session.active_run %}">{% trans "Taxonomy" %}</a></li>
      <li class="divider" tabindex="-1"></li>
      {% if session.emperor %}
      <li><a href="{% url 'results:pcoa' session.active_run %}">PCoA</a></li>
      {% endif %}
    </ul>
  </div>
</li>
{% block sidenav_items_2 %}
{% endblock %}
{% endblock %}

web/django/results/templates/results/taxonomy.html
{% extends "app/base.html" %}
{% load materializecss %}

{% block header_include %}
{% include "results/taxonomy_header.html" %}
{% endblock header_include %}

{% block content %}
{% load static %}
<div class="tax-content">
  <div class="row" style="padding:0;margin:0;flex: 1 0 auto;">
    {% if kronaplots|length > 1 %}
    {% for plot in kronaplots %}
    <div class="col s12 m12 l6" style="padding:0;margin:0;flex: 1 0 auto;">
      <iframe class="krona-iframe" src="{% url 'results:krona_iframe' plot.id %}"></iframe>
    </div>
    {% endfor %}
    {% else %}
    {% for plot in kronaplots %}
    <div class="col s12 m12 l12" style="padding:0;margin:0;flex: 1 0 auto;">
      <iframe class="krona-iframe" src="{% url 'results:krona_iframe' plot.id %}"></iframe>
    </div>
    {% endfor %}
    {% endif %}
  </div>
</div>

{% endblock %}

{% block custom_js %}
<script>
    $(document).ready(function () {
        $('footer').prop("hidden", true);
        // $('html').css("overflow-y","hidden")
        var rc = $('#results-collapsible');
        rc.removeClass("active");
        rc.find(".collapsible-body").css("display", "none");
        $('.collapsible').collapsible();
    })
</script>
{% endblock %}

web/django/results/templates/results/taxonomy_header.html
{% extends "results/results_header.html" %}
{% load materializecss %}
{% load i18n %}
{% block sidenav_items_2 %}

<li class="divider no-margin"></li>
<li class="active">
  <div class="collapsible-header">{% trans "Samples" %}</div>
  <div class="collapsible-body">
      <label>
        <input class="btn" id="check" name="samples_all" type="checkbox" {{ session.all_samples_active }}/>
        <span>Select all</span>
      </label>
      {{ samples_form|materializecss }}
  </div>
</li>

{% endblock %}