web/django/MetagenApp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n'), name="set_language"),
]

urlpatterns += i18n_patterns(
    path("", include("app.urls")),
    path('pipeline/', include("pipeline.urls")),
    path("results/", include("results.urls")),
)

web/django/app/urls.py
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = "app"
urlpatterns = [
    path("", views.index_view, name="index"),
    re_path(r'^ajax/request_lock/$', views.request_lock, name='request_lock')] \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#               + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \

web/django/pipeline/urls.py
from django.urls import path

from . import views

app_name = "pipeline"
urlpatterns = [
    path("config/", views.pipeline_config, name="config"),
    path("config/<uuid:run_id>/", views.pipeline_param_config, name="pconfig"),
    path("config/<uuid:run_id>/assign/", views.pipeline_param_assign, name="passign"),
    path("logs/", views.pipeline_logs, name="logs"),
    path("logs/<uuid:run_id>/", views.pipeline_logs_samples, name="run_logs"),
    path("logs/<uuid:run_id>/steps/", views.pipeline_logs_steps, name="run_logs_steps"),
    path("upload/", views.pipeline_upload, name="upload"),
    path("edit/", views.pipeline_edit, name="edit"),
    path("edit/edit/<uuid:run_id>", views.pipeline_run_edit, name="run_edit"),
    path("edit/delete/<uuid:run_id>", views.pipeline_delete, name="delete"),
]

web/django/pipeline/models.py
import uuid

from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _
from django.db import models

from results.models import PipelineRun, Sample, SampleParameter, SampleParameterPreset


class PipelineTrim(models.Model):
    class Meta:
        verbose_name = _("trimming parameter")
        verbose_name_plural = _("trimming parameters")

    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)
    run = models.ForeignKey(PipelineRun,
                            on_delete=models.CASCADE,
                            default=0)
    leading_quality = models.IntegerField(default=20,
                                          choices=[(x, x) for x in range(1, 31)],
                                          validators=[MinValueValidator(0), MaxValueValidator(30)])
    trailing_quality = models.IntegerField(default=20,
                                           choices=[(x, x) for x in range(1, 31)],
                                           validators=[MinValueValidator(0), MaxValueValidator(30)])
    minimum_length = models.IntegerField(default=70,
                                         choices=[(x, x) for x in range(50, 310, 10)],
                                         validators=[MinValueValidator(50), MaxValueValidator(300)])
    sliding_window = models.IntegerField(default=4,
                                         choices=[(x, x) for x in range(1, 11)],
                                         validators=[MinValueValidator(1), MaxValueValidator(10)])
    sliding_window_quality = models.IntegerField(default=20,
                                                 choices=[(x, x) for x in range(1, 61)],
                                                 validators=[MinValueValidator(10), MaxValueValidator(60)])
    illumina_clipping = models.CharField(
        choices=[(x, x) for x in [_("No Clipping"), "TruSeq2-PE", "TruSeq3-PE-2", "TruSeq3-PE", "NexteraPE-PE"]],
        default=_("No Clipping"),
        max_length=13)

    crop = models.IntegerField(default=0,
                               choices=[(x, x) for x in range(0, 11)],
                               validators=[MinValueValidator(0), MaxValueValidator(10)])
    head_crop = models.IntegerField(default=0,
                                    choices=[(x, x) for x in range(0, 11)],
                                    validators=[MinValueValidator(0), MaxValueValidator(10)])


class PipelineTrimClip(models.Model):
    class Meta:
        verbose_name = _("clipping parameter")
        verbose_name_plural = _("clipping parameters")

    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)
    run = models.ForeignKey(PipelineRun,
                            on_delete=models.CASCADE,
                            default=0)
    seed_mismatches = models.IntegerField(default=2,
                                          choices=[(x, x) for x in range(1, 101)],
                                          validators=[MinValueValidator(1), MaxValueValidator(100)])
    palindrome_clip_theshold = models.IntegerField(default=20,
                                                   choices=[(x, x) for x in range(10, 101)],
                                                   validators=[MinValueValidator(10), MaxValueValidator(100)])
    simple_clipping_theshold = models.IntegerField(default=30,
                                                   choices=[(x, x) for x in range(10, 101)],
                                                   validators=[MinValueValidator(10), MaxValueValidator(100)])
    # default 0 for no minAdapterLength
    minimum_adapter_length = models.IntegerField(default=0,
                                                 choices=[(x, x) for x in range(0, 31)],
                                                 validators=[MinValueValidator(0), MaxValueValidator(30)])


class PipelineLog(models.Model):
    class Meta:
        verbose_name = _("log message")
        verbose_name_plural = _("log messages")

    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)
    run = models.ForeignKey(PipelineRun,
                            on_delete=models.CASCADE)
    sample = models.ForeignKey(Sample,
                               on_delete=models.CASCADE,
                               blank=True,
                               null=True)
    level = models.CharField("level", max_length=10)
    tool = models.CharField(_("tool"),
                            max_length=50)
    message = models.TextField(_("message"))
    timestamp = models.DateTimeField(_("timestamp"))

web/django/results/models.py
import os
import uuid

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey


class PipelineRun(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)
    analysis_en = models.CharField(_("english name"),
                                   max_length=20,
                                   unique=True)
    analysis_de = models.CharField(_("german name"),
                                   max_length=20,
                                   blank=True)
    mode = models.CharField(_("mode"),
                            choices=[(x, x) for x in ["WGS", "16S"]],
                            default="16S",
                            max_length=3)
    cpu_cores = models.IntegerField(_("CPU cores"),
                                    choices=[(x, x) for x in range(1, os.cpu_count() + 1)],
                                    default=os.cpu_count() - 1)
    analysis_date = models.DateTimeField(_("date"), default=timezone.now)
    status = models.CharField(max_length=10, default="new")
    description_en = models.TextField(_("description (en)"), max_length=500, blank=True)
    description_de = models.TextField(_("description (ge)"), max_length=500, blank=True)
    details_en = models.TextField(_("detailed description (en)"), max_length=10000, blank=True)
    details_de = models.TextField(_("detailed description (ge)"), max_length=10000, blank=True)
    image = models.ImageField(_("image"), blank=True)

    def __str__(self):
        return self.analysis_en


def set_upload_path(instance, filename):
    return f"input/{instance.run.analysis_en}/{filename}"


class Sample(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    run = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    name = models.CharField(_("Sample Name"), max_length=20)
    sample_file_fwd = models.FileField(_("forward file"), upload_to=set_upload_path)
    sample_file_rev = models.FileField(_("reverse file"), upload_to=set_upload_path)


class KronaPlot(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    run_id = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    sample_id = models.ForeignKey(Sample, on_delete=models.CASCADE)
    kronahtml = models.TextField("kronahtml")


class EmperorPlot(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    run_id = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    rank = models.CharField("rank", max_length=1)
    emperordata_en = models.TextField("emperordata")
    emperordata_de =  models.TextField("emperordata", blank=True, null=True)


class Taxon(MPTTModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True,
                            related_name="children")
    sample_id = models.ForeignKey(Sample, on_delete=models.CASCADE)
    run_id = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    percentage = models.FloatField()
    fragments_root = models.IntegerField()
    fragments = models.IntegerField()
    abundance = models.IntegerField()
    rank = models.CharField(max_length=4)
    tax_id = models.CharField(max_length=30, blank=True, null=True)
    name = models.CharField(max_length=200)

    class MPTTMeta:
        order_insertion_by = ['name']


class SampleParameterPreset(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    run = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    parameter_en = models.CharField("parameter (english)", max_length=20)
    parameter_de = models.CharField("parameter (german)", max_length=20)
    datatype = models.CharField(_("data type"), max_length=11)
    value_1 = models.CharField(_("value 1"), max_length=20, blank=True, null=True)
    value_2 = models.CharField(_("value 2"), max_length=20, blank=True, null=True)
    value_3 = models.CharField(_("value 3"), max_length=20, blank=True, null=True)
    value_4 = models.CharField(_("value 4"), max_length=20, blank=True, null=True)
    value_5 = models.CharField(_("value 5"), max_length=20, blank=True, null=True)
    value_6 = models.CharField(_("value 6"), max_length=20, blank=True, null=True)
    value_7 = models.CharField(_("value 7"), max_length=20, blank=True, null=True)
    value_8 = models.CharField(_("value 8"), max_length=20, blank=True, null=True)
    value_9 = models.CharField(_("value 9"), max_length=20, blank=True, null=True)
    value_10 = models.CharField(_("value 10"), max_length=20, blank=True, null=True)
    value_1_de = models.CharField(_("value 1 (ge)"), max_length=20, blank=True, null=True)
    value_2_de = models.CharField(_("value 2 (ge)"), max_length=20, blank=True, null=True)
    value_3_de = models.CharField(_("value 3 (ge)"), max_length=20, blank=True, null=True)
    value_4_de = models.CharField(_("value 4 (ge)"), max_length=20, blank=True, null=True)
    value_5_de = models.CharField(_("value 5 (ge)"), max_length=20, blank=True, null=True)
    value_6_de = models.CharField(_("value 6 (ge)"), max_length=20, blank=True, null=True)
    value_7_de = models.CharField(_("value 7 (ge)"), max_length=20, blank=True, null=True)
    value_8_de = models.CharField(_("value 8 (ge)"), max_length=20, blank=True, null=True)
    value_9_de = models.CharField(_("value 9 (ge)"), max_length=20, blank=True, null=True)
    value_10_de = models.CharField(_("value 10 (ge)"), max_length=20, blank=True, null=True)


class SampleParameter(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sample = models.ForeignKey(Sample, on_delete=models.CASCADE)
    run = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    name_en = models.CharField(_("parameter (english)"), max_length=20)
    name_de = models.CharField(_("parameter (german)"), max_length=20)
    value = models.CharField(_("value"), max_length=20)
    value_de = models.CharField(_("value (german)"), max_length=20)
    datatype = models.CharField(_("type"), max_length=11)
    order = models.IntegerField(null=True)


class PipelineQC(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    run_id = models.ForeignKey(PipelineRun, on_delete=models.CASCADE)
    sample_id = models.ForeignKey(Sample, on_delete=models.CASCADE)
    fastqc_fwd = models.TextField("fastqc_fwd")
    fastqc_rev = models.TextField("fastqc_rev")
    fastqc_fwd_trim = models.TextField("fastqc_fwd_trim", default="")
    fastqc_rev_trim = models.TextField("fastqc_rev_trim", default="")

web/django/pipeline/templates/pipeline/config.html
{% extends "app/base.html" %}
{% load materializecss %}
{% load i18n %}
{% block content %}
<div class="container">
  <form action="" class="form-horizontal" enctype="multipart/form-data" id="main-config" method="POST">
    {% csrf_token %}
    {{ formset.management_form }}
    <div class="row">
      <h3>{% trans "Pipeline Configuration" %}</h3>
      <div class="input-field col s12 m3">{{ form.analysis_en|materializecss }}</div>
       <div class="input-field col s12 m3">{{ form.analysis_de|materializecss }}</div>
      <div class="input-field col s6 m2">{{ form.mode|materializecss }}</div>
      <div class="input-field col s6 m2">{{ form.cpu_cores|materializecss }}</div>
      <div class="input-field col s12 m2">{{ form.image|materializecss }}</div>
      <div class="input-field col s12 m6">{{ form.description_en|materializecss }}</div>
      <div class="input-field col s12 m6">{{ form.description_de|materializecss }}</div>
    </div>
    <div class="row">
      <h4>{% trans 'Trimming parameter' %} </h4>
      <div class="col s6 m2 input-field">{{ trim_form.leading_quality|materializecss }}</div>
      <div class="col s6 m2 input-field">{{ trim_form.trailing_quality|materializecss }}</div>
      <div class="col s4 m2 input-field">{{ trim_form.minimum_length|materializecss }}</div>
      <div class="col s4 m2 input-field">{{ trim_form.sliding_window|materializecss }}</div>
      <div class="col s4 m2 input-field">{{ trim_form.sliding_window_quality|materializecss }}</div>
      <div class="col s4 m1 input-field">{{ trim_form.crop|materializecss }}</div>
      <div class="col s4 m1 input-field">{{ trim_form.head_crop|materializecss }}</div>
    </div>
    <div class="row">
      <!--                  <div class="col s2 input-field">-->
      <!--                <select id="clipping">-->
      <!--                    {% for x, y in trim_form.fields.illumina_clipping.choices %}-->
      <!--                    <option value="{{ x }}" {% if trim_form.fields.illumina_clipping.value == x %} selected {% endif %}>{{ y }}</option>-->
      <!--                    {% endfor %}-->
      <!--                </select>-->
      <!--                      <label for="clipping">{{ trim_form.fields.illumina_clipping.label }} </label>-->
      <!--            </div>-->
      
      <div class="col s6 m8 l4 clip-select">{{ trim_form.illumina_clipping|materializecss }}</div>
      <div class="col s6 m4 l2 clip">{{ trim_clip_form.seed_mismatches|materializecss }}</div>
      <div class="col s4 m4 l2 clip">{{ trim_clip_form.palindrome_clip_theshold|materializecss }}</div>
      <div class="col s4 m4 l2 clip">{{ trim_clip_form.simple_clipping_theshold|materializecss }}</div>
      <div class="col s4 m4 l2 clip">{{ trim_clip_form.minimum_adapter_length|materializecss }}</div>
    
    </div>
    
    <h4>{% trans "Samples" %}</h4>
    {% for f in formset %}
    <div class="row form-row">
      <div class="input-group">
        <div class="col s6 m4">{{ f.name|materializecss }}</div>
        <div class="col s3 m4">{{ f.sample_file_fwd|materializecss }}</div>
        <div class="col s3 m4">{{ f.sample_file_rev|materializecss }}</div>
      </div>
      <div class="input-group-append">
        <button class="btn add-form-row">+</button>
      </div>
    </div>
    {% endfor %}
    <button class="btn-large right btn-bottom" type="submit"><i class="material-icons right dd-icon">navigate_next</i></button>
  </form>
</div>
{% endblock %}

{% block custom_js %}
{% load static %}
<script src="{% static 'formset_handler.js' %}" type="text/javascript"></script>
<script>
      $('a[data-target="results-dd"]>img').attr("src", "{% static 'app/img/research-grey.svg' %}");
      $('a[data-target="results-dd"]').addClass("disabled");
</script>
{% endblock %}

  {% block footer_include %}
  {% endblock footer_include %}

web/django/pipeline/templates/pipeline/edit.html
{% extends "app/base.html" %}
{% load render_table from django_tables2 %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="container">
  <h4>{% trans "Runs in Database:" %}</h4>
  {% render_table run_table %}
</div>
{% endblock %}

  {% block footer_include %}
  {% endblock footer_include %}

{% block custom_js %}
<script>
      $('a[data-target="results-dd"]>img').attr("src", "{% static 'app/img/research-grey.svg' %}");
      $('a[data-target="results-dd"]').addClass("disabled");
</script>

{% endblock %}

web/django/pipeline/templates/pipeline/logs_base.html
{% extends "app/base.html" %}
{% load materializecss %}
{% load i18n %}

{% block header_include %}
{% include "app/base_header.html" %}
{% endblock header_include %}

{% block content %}

  {% block log_content %}
<p style="margin-left: 30px">{% trans "No run selected." %}</p>
  {% endblock log_content %}


{% endblock content %}

  {% block footer_include %}
  {% endblock footer_include %}

{% block custom_js %}

{% load static %}

{% endblock %}

web/django/pipeline/templates/pipeline/logs_run.html
{% extends "pipeline/logs_base.html" %}
{% load materializecss %}

{% block header_include %}
{% include "pipeline/logs_run_header.html" %}
{% endblock header_include %}

{% block log_content %}
<form action="{% url 'pipeline:run_logs_steps' session.active_run %}" enctype="multipart/form-data" id="steps-form"
      method="POST">
  {% csrf_token %}
  <div class="row" id="arrow-row">
    <div class="col">
      <div id="id_steps_form-steps">
        <ul id="arrow-list">
          {% for choice in steps_form.step.field.choices %}
          <li>
            <label>
            <input type="checkbox" name="steps_form-step" value="{{ choice.0 }}"
                   id="id_steps_form-steps_{{ forloop.counter0 }}"
                   {% if choice.0 in session.active_logs %} checked="checked"{% endif %}>
            <span>{{ choice.1 }}</span>
          </label>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <div class="divider"></div>
  <div class="row">
      <div class="log-content col">
    {% if logs %}
    {% for log in logs %}
    <p>{{ log.timestamp }} {{ log.tool }} {{ log.level }}: </p>
    <p class="log-text">{{ log.message }}</p>
    {% endfor %}
    {% endif %}
  </div>
  </div>
</form>
  {% endblock log_content %}

web/django/pipeline/templates/pipeline/logs_run_header.html
{% extends "app/base_header_fixed.html" %}
{% load materializecss %}
{% load i18n %}

{% block sidenav_items %}

<ul class="collapsible">
  <li>
    <div class="collapsible-header">{% trans "Runs" %}</div>
    <div class="collapsible-body">
      <ul>
        {% for run in runs %}
        <li><a href="{% url 'pipeline:logs' %}">{{ run }}</a></li>
        {% endfor %}
      </ul>
    </div>
  </li>
  <li class="active">
  <div class="collapsible-header">{% trans "Samples" %}</div>
  <div class="collapsible-body" style="padding-left: 1em">
      <label>
        <input class="btn" id="check" name="samples_all" type="checkbox" {{ session.all_samples_active }}/>
        <span>{% trans "Select all" %}</span>
      </label>
      {{ samples_form|materializecss }}
  </div>
</li>
</ul>

{% endblock %}

web/django/pipeline/templates/pipeline/passign.html
{% extends "app/base.html" %}
{% load materializecss %}
{% load static %}
{% block content %}
{% load i18n %}
<div class="container">
  <form action="" class="form-horizontal" enctype="multipart/form-data" id="main-config" method="POST">
    <h2 class="mt-5">Sample Parameter Definition</h2>
    {% csrf_token %}
    {% for formset in formsets %}
    <div class="row">
      <h6>{{formset.prefix}}</h6>
      {{ formset|materializecss:'s6 m3 l2'}}
    </div>
    {% endfor %}
    <div class="row">
      <div class="col s3  offset-s9">
        <button class="btn-large right btn-bottom" type="submit">{% trans 'Start Run' %}<i class="material-icons right">send</i></button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

  {% block footer_include %}
  {% endblock footer_include %}

{% block custom_js %}
<script>
      $('a[data-target="results-dd"]>img').attr("src", "{% static 'app/img/research-grey.svg' %}");
      $('a[data-target="results-dd"]').addClass("disabled");
</script>
{% endblock %}

web/django/pipeline/templates/pipeline/pconfig.html
{% extends "app/base.html" %}
{% load materializecss %}
{% block content %}
<div class="container">
  <form action="" class="form-horizontal" enctype="multipart/form-data" id="main-config" method="POST">
    <h3>Sample Parameter Definition</h3>
    {% csrf_token %}
    {{ formset.management_form }}
    {% for errors in formset.errors %}
     {% for k, v in errors.items %}
      {% if k == "all" %} <p class="help-block orange-text">{{ v }}</p> {% endif %}
    {% endfor %}
    {% endfor %}
    {% for f in formset %}
    <div class="row form-row">
      <div class="input-group">
        <div class="row pconf">
          <div class="col s3 input-field">{{ f.parameter_en|materializecss }}</div>
          <div class="col s3 input-field">{{ f.parameter_de|materializecss }}</div>
          <div class="col s2 input-field">{{ f.datatype|materializecss }}</div>
        </div>
      <div class="row pval">
          <div class="col s1 s10ths input-field">{{ f.value_1|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_2|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_3|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_4|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_5|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_6|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_7|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_8|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_9|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_10|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_1_de|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_2_de|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_3_de|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_4_de|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_5_de|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_6_de|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_7_de|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_8_de|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_9_de|materializecss }}</div>
          <div class="col s1 s10ths input-field">{{ f.value_10_de|materializecss }}</div>
        </div>
      </div>
      <div class="input-group-append">
        <button class="btn add-form-row">+</button>
      </div>
    </div>
    {% endfor %}
    <div class="row ">
      <div class="col s2">
        <a class="btn-large right btn-bottom" href="{% url 'pipeline:config' %}">
          <i class="material-icons right dd-icon">navigate_before</i>
        </a>
      </div>
      <div class="col s2 offset-s8">
        <button class="btn-large right btn-bottom" type="submit">
          <i class="material-icons right dd-icon">navigate_next</i>
        </button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

  {% block footer_include %}
  {% endblock footer_include %}

{% block custom_js %}
{% load static %}
<script src="{% static 'formset_handler.js' %}" type="text/javascript"></script>
<script>
    $(document).on("DOMNodeInserted", function (e) {
        if ($('div .form-row').length > 9) {
            $("button.add-form-row:last").hide();
        }
    });
    $(document).on("DOMNodeRemoved", function (e) {
        if ($('div .form-row').length > 9) {
            $("button.add-form-row:last").show();
        }
    });

      $('a[data-target="results-dd"]>img').attr("src", "{% static 'app/img/research-grey.svg' %}");
      $('a[data-target="results-dd"]').addClass("disabled");
</script>
{% endblock %}

web/django/pipeline/templates/pipeline/run_edit.html
{% extends "app/base.html" %}
{% load materializecss %}
{% load i18n %}

{% block content %}
<div class="container">
  <h4>{% trans "Edit Run:" %}</h4>
  <form action="" enctype="multipart/form-data" id="edit-form" method="POST">
    {% csrf_token %}
        {{ run_form.management_form }}
    <div class="row">
      <div class="col s12 l6">
        <img class="img-edit" src="{{ image.url }}">
      </div>
      <div class="col s12 l6">
        <div style="display: inline-block">
          {{run_form.analysis_en|materializecss}}
        {{run_form.status|materializecss}}
        </div>
        
        <div class="file-field input-field" style="display: inline-block">
          <div class="btn">
            <span>{% trans "Change Image" %}</span>
            <input type="file" name="image" accept="image/*" id="id_image">
          </div>
          <div class="file-path-wrapper" >
            <input class="file-path-validate" type="text">
          </div>
        </div>
        </div>
    </div>
    <div class="row">
      <div class="col s12">
        {{run_form.description_en|materializecss}}
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        {{run_form.description_de|materializecss}}
      </div>
    </div>
    <button class="btn" type="submit">{% trans "Save"%}</button>
  </form>
</div>
{% endblock %}

  {% block footer_include %}
  {% endblock footer_include %}

{% block custom_js %}
<!--<script>-->
<!--    $('#upload-submit').click(function () {-->
<!--        $("#upload-form").submit();-->
<!--    });-->
<!--    {% if message %}-->
<!--    $(document).ready(function () {-->
<!--      alert('{{ message }}');-->
<!--    });-->
<!--    {% endif %}-->
<!--    -->
<!--</script>-->
{% endblock %}

web/django/pipeline/templates/pipeline/upload.html
{% extends "app/base.html" %}
{% load materializecss %}
{% block content %}
{% load static %}
{% load i18n %}
<div class="container">

  
  <h4>{% trans "Upload Results" %}</h4>
  {% blocktrans %}
  <p>Select a <i>results.zip</i> file of a previously processed run from your File System and upload to the database.</p>
  {% endblocktrans %}
  <form action="" enctype="multipart/form-data" id="upload-form" method="POST">
  {{ upload_form|materializecss }}
  <button id="upload-submit" type="submit" class="btn-large waves-effect waves-light right">{% trans "Submit" %}<i class="material-icons right">send</i></button>
  </form>
</div>

{% endblock %}

  {% block footer_include %}
  {% endblock footer_include %}

{% block custom_js %}
<script>
  
    $('#upload-submit').click(function () {
        $("#upload-form").submit();
    });
    {% if message %}
    $(document).ready(function () {
      alert('{{ message }}');
    });
    {% endif %}

    $('a[data-target="results-dd"]>img').attr("src", "{% static 'app/img/research-grey.svg' %}");
    $('a[data-target="results-dd"]').addClass("disabled");
</script>
{% endblock %}